[package]
name = "pushgp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
byte-slice-cast = "1.0.0"
fnv = "1.0.7"
nom = "6.2.1"
pushgp-macros = { path = "../pushgp-macros" }
rand = "0.8"